name: haskell-platio-example
version: 0.1.0.0

default-extensions:
- BlockArguments
- DataKinds
- DeriveGeneric
- FlexibleContexts
- GADTs
- LambdaCase
- OverloadedStrings
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StrictData
- TemplateHaskell
- TypeApplications
- TypeOperators
- TypeFamilies

dependencies:
- aeson >= 1.4 && < 1.5
- async >= 2.2 && < 2.3
- base >= 4.7 && < 5
- bytestring >= 0.10 && < 0.11
- exceptions >= 0.10 && < 0.11
- http-client >= 0.6 && < 0.7
- http-client-tls >= 0.3 && < 0.4
- optparse-applicative >= 0.14 && < 0.15
- polysemy >= 1.2 && < 1.3
- text >= 1.2 && < 1.3

ghc-options:
- -Wall
- -Wno-name-shadowing

library:
  source-dirs: src

executables:
  haskell-platio-example-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-platio-example

  haskell-platio-example-free:
    main: Main.hs
    source-dirs: app/free
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-platio-example

tests:
  haskell-platio-example-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-platio-example
